### PR TITLE
Kw fire employees

### PR DESCRIPTION
**Pull request by keosha-w**
Please pull down and make sure that when you click on the fire button the employee is removed from the API.

### CODE REVIEW

**Comment by AshHimura** [comment]
Viewed while you were working on this, approval granted

**Comment by AshHimura** [comment]
Employee firing does work, approved

**Comment by JMR-dev** [comment]
approved, still iterating to secure fire ability from regular users.

**Comment by JMR-dev** [comment]
looks good, able to rerender state after firing an employee.

**Pull request merged**
